const listaProdutos = [
  ["https://caene-unb.github.io/geladeira-unb/imgs/moster_black.webp", "Monster Original (Preto)", "", "ENERGÉTICO", "9.00"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/monster_preto_zero.webp", "Monster Original (Preto ZERO)", "", "ENERGÉTICO", "9.00"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/monster_branco.webp", "Monster Ultra (Branco)", "", "ENERGÉTICO", "9.00"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/monster_mango_logo.webp", "Monster Mango LOCO", "", "ENERGÉTICO", "9.00"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/monster_watermelon.webp", "Monster Ultra Wattermellow (Vermelho)", "", "ENERGÉTICO", "9.00"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/monster_preto_zero.webp", "Monster Preto+Azul", "", "ENERGÉTICO", "9.00"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/monster_khaotic.webp", "Monster Ultra Caotic (Laranja - Pecego)", "", "ENERGÉTICO", "9.00"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/monster_pacific_punch.webp", "Monster Rosa", "", "ENERGÉTICO", "9.00"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/monster_pipeline_punch.webp", "Monster Pacific Punch", "", "ENERGÉTICO", "9.00"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/paçoca.webp", "Paçoquinha", "", "DOCES", "1.00"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/kitkat_dark.webp", "KitKat Dark", "", "DOCES", "4.50"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/kitkat_tradicional.webp", "KitKat Tradicional", "", "DOCES", "4.50"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/jujuba_gomets.webp", "Jujuba Gumetes", "Sabores: iogurte e frutas ", "DOCES", "1.00"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/bis_extra_black.webp", "Bis Extra Black", "", "DOCES", "4.50"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/bis_extra.webp", "Bis Extra", "", "DOCES", "4.50"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/coca_mini.webp", "Mini Coca", "", "BEBIDA", "2.50"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/mini_fanta.webp", "Mini Fanta", "", "BEBIDA", "2.50"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/mini_guarana.webp", "Mini Guaraná", "", "BEBIDA", "2.50"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/agua_com_gas.webp", "Aguá com gás", "", "BEBIDA", "4.00"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/bombomLimao.webp", "Bom Bom Limão", "Com recheio cremoso de limão da fruta", "", "4.00"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/bombomMorango.webp", "Bom Bom Morango", "Com recheio cremoso de morango da fruta", "", "4.00"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/bombomMaracuja.webp", "Bom Bom de Maracujá", "Com recheio cremoso de maracujá da fruta", "", "4.00"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/paodemel.png", "Pão de Mel", "Com recheio cremoso de café", "", "5.00"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/mateleaoGas.webp", "Mate Leão com Gás", "", "", "5.50"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/pinklemonade.webp", "Pink Lemonade St.Pierre", "", "", "5.50"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/fantaLaranjaLata.jpeg", "Fanta Laranja Lata", "", "", "4.00"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/ShewppesLata.jpeg", "Schweppes Lata", "", "", "4.00"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/guaranaMineiro.png", "Guaraná Mineiro", "", "", "2.50"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/fantaLaranjaLata.jpeg", "Powerade Laranja", "", "", "8.00"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/poweradeMixDeFrutas.webp", "Powerade Mix de Fruta", "", "", "8.00"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/aguasemgas.webp", "Água sem gás", "", "", "3.00"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/geladinho.webp", "Geladinho Sabores", "", "", "1.50"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/tictac.jpeg", "TicTac Sabores", "Mix de sabores", "", "4.00"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/snickersOriginal.webp", "Snickers", "", "", "5.00"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/snickersDark.webp", "Snickers Dark", "", "", "5.00"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/snickersPeMoleque.webp
", "Snickers Pé de Moleque", "", "", "5.00"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/balinhaAzeinha.jpg", "Azedinha", "Drops azedinho sabor Uva", "", "1.50"],
];
