const listaProdutos = [
    ["https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSTNnp5qp6ZbOgyBVXG1Y3vDcNetA3rbhXKbpRMRGFSu-P85_74ecWtIBqL_2a-fTNVRr9JfgxIYR_JfqNXFUSJ-0V6WHT2FUPcIVVK0nnC5FD2UPPcOW7HlMdxguVBjSsn4hyf9jcNMQ&usqp=CAc", "Paçoquinha", "Teste", "DOCES", "1.00"],
    ["a", "KitKat Dark", "", "DOCES", "4.50"],
    ["", "KitKat Tradicional", "", "DOCES", "4.50"],
    ["aa", "Jujuba Gumetes", "", "DOCES", "1.00"],
    ["a", "Bis Extra Black", "", "DOCES", "4.50"],
    ["a", "Bis Extra", "", "DOCES", "4.50"],
    ["a", "Monster Original (Preto)", "", "ENERGÉTICO", "9.00"],
    ["a", "Monster Original (Preto ZERO)", "", "ENERGÉTICO", "9.00"],
    ["a", "Monster Ultra (Branco)", "", "ENERGÉTICO", "9.00"],
    ["a", "Monster Mango LOCO", "", "ENERGÉTICO", "9.00"],
    ["", "Monster Ultra Wattermellow (Vermelho)", "", "ENERGÉTICO", "9.00"],
    ["", "Monster Preto+Azul", "", "ENERGÉTICO", "9.00"],
    ["", "Monster Ultra Caotic (Laranja - Pecego)", "", "ENERGÉTICO", "9.00"],
    ["", "Monster Rosa", "", "ENERGÉTICO", "9.00"],
    ["", "Monster Pacific Punch", "", "DOCES", "9.00"],
    ["", "Mini Coca", "", "BEBIDA", "2.50"],
    ["", "Mini Fanta", "", "BEBIDA", "2.50"],
    ["", "Mini Guaraná", "", "BEBIDA", "2.50"],
    ["", "Aguá com gás", "", "BEBIDA", "3.00"],
  ];