const listaProdutos = [
  ["https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSTNnp5qp6ZbOgyBVXG1Y3vDcNetA3rbhXKbpRMRGFSu-P85_74ecWtIBqL_2a-fTNVRr9JfgxIYR_JfqNXFUSJ-0V6WHT2FUPcIVVK0nnC5FD2UPPcOW7HlMdxguVBjSsn4hyf9jcNMQ&usqp=CAc", "Paçoquinha", "Teste", "DOCES", "1.00"],
  ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxVGjZYPH7e7Cv6RAznxTTQvGBtb77zPpBKQ&s", "KitKat Dark", "", "DOCES", "4.50"],
  ["https://docemalu.vtexassets.com/arquivos/ids/5355969/111163-1.jpg?v=638576006103130000", "KitKat Tradicional", "", "DOCES", "4.50"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/jujuba_gomets.webp", "Jujuba Gumetes", "", "DOCES", "1.00"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/bis_extra_black.webp", "Bis Extra Black", "", "DOCES", "4.50"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/bis_extra.webp", "Bis Extra", "", "DOCES", "4.50"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/moster_black.webp", "Monster Original (Preto)", "", "ENERGÉTICO", "9.00"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/monster_preto_zero.webp", "Monster Original (Preto ZERO)", "", "ENERGÉTICO", "9.00"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/monster_branco.webp", "Monster Ultra (Branco)", "", "ENERGÉTICO", "9.00"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/monster_mango_logo.webp", "Monster Mango LOCO", "", "ENERGÉTICO", "9.00"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/monster_watermelon.webp", "Monster Ultra Wattermellow (Vermelho)", "", "ENERGÉTICO", "9.00"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/monster_preto_zero.webp", "Monster Preto+Azul", "", "ENERGÉTICO", "9.00"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/monster_khaotic.webp", "Monster Ultra Caotic (Laranja - Pecego)", "", "ENERGÉTICO", "9.00"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/monster_pacific_punch.webp", "Monster Rosa", "", "ENERGÉTICO", "9.00"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/monster_pipeline_punch.webp", "Monster Pacific Punch", "", "DOCES", "9.00"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/coca_mini.webp", "Mini Coca", "", "BEBIDA", "2.50"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/mini_fanta.webp", "Mini Fanta", "", "BEBIDA", "2.50"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/mini_guarana.webp", "Mini Guaraná", "", "BEBIDA", "2.50"],
  ["https://caene-unb.github.io/geladeira-unb/imgs/agua_com_gas.webp", "Aguá com gás", "", "BEBIDA", "3.00"],
];
